import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useLocalSearchParams } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { useState } from "react";

import { ScreenBack } from "@/components/screen-back";
import { ScreenContainer } from "@/components/screen-container";
import { services } from "@/lib/business-content";

export default function ServiceDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const service = services.find((item) => item.id === id);
  const [checked, setChecked] = useState<number[]>([]);
  if (!service) return <ScreenContainer className="p-5"><ScreenBack title="Layanan" /><Text style={styles.notFound}>Layanan tidak ditemukan.</Text></ScreenContainer>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><FlatList data={service.checklist} keyExtractor={(item, index) => `${item}-${index}`} contentContainerStyle={styles.list} ListHeaderComponent={<><ScreenBack title="Layanan" /><View style={styles.hero}><View style={styles.icon}><MaterialIcons name={service.icon as never} size={25} color="#986018" /></View><Text style={styles.heroTitle}>{service.title}</Text><Text style={styles.heroText}>{service.summary}</Text></View><View style={styles.note}><MaterialIcons name="info-outline" size={19} color="#124C43" /><Text style={styles.noteText}>{service.note}</Text></View><Text style={styles.heading}>Yang bisa disiapkan</Text><Text style={styles.subheading}>Tandai saat dokumen atau informasi sudah tersedia.</Text></>} renderItem={({ item, index }) => { const done = checked.includes(index); return <Pressable onPress={() => setChecked((current) => current.includes(index) ? current.filter((value) => value !== index) : [...current, index])} style={({ pressed }) => [styles.row, done && styles.rowDone, pressed && styles.pressed]} accessibilityRole="checkbox" accessibilityState={{ checked: done }}><View style={[styles.box, done && styles.boxDone]}>{done ? <MaterialIcons name="check" size={16} color="#FFFFFF" /> : null}</View><Text style={[styles.rowText, done && styles.rowTextDone]}>{item}</Text></Pressable>; }} ListFooterComponent={<View style={styles.footer}><View style={styles.footerTop}><MaterialIcons name="verified-user" size={18} color="#124C43" /><Text style={styles.footerTitle}>Gunakan sumber resmi</Text></View><Text style={styles.footerText}>Checklist ini adalah persiapan awal. Konfirmasi persyaratan terbaru melalui sumber resmi sebelum mengirim data atau dokumen.</Text></View>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ list: { padding: 20, paddingTop: 8, paddingBottom: 36 }, notFound: { color: "#14211F", fontSize: 16 }, hero: { borderRadius: 26, backgroundColor: "#FFF4DC", padding: 20 }, icon: { width: 48, height: 48, borderRadius: 16, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" }, heroTitle: { color: "#46350E", fontSize: 26, lineHeight: 32, fontWeight: "800", marginTop: 16 }, heroText: { color: "#735D23", fontSize: 14, lineHeight: 21, marginTop: 7 }, note: { marginTop: 13, borderRadius: 18, padding: 15, backgroundColor: "#E8F3EE", flexDirection: "row", alignItems: "flex-start", gap: 10 }, noteText: { flex: 1, color: "#38655A", fontSize: 13, lineHeight: 19 }, heading: { color: "#14211F", fontSize: 20, lineHeight: 26, fontWeight: "800", marginTop: 26 }, subheading: { color: "#5E706B", fontSize: 14, lineHeight: 21, marginTop: 4 }, row: { minHeight: 70, backgroundColor: "#FFFFFF", borderRadius: 18, borderWidth: 1, borderColor: "#E0E7E3", padding: 15, marginTop: 10, flexDirection: "row", alignItems: "center", gap: 12 }, rowDone: { borderColor: "#B9DCCB", backgroundColor: "#F1F8F4" }, box: { width: 26, height: 26, borderRadius: 8, borderWidth: 1.5, borderColor: "#A4B5AE", alignItems: "center", justifyContent: "center" }, boxDone: { backgroundColor: "#127352", borderColor: "#127352" }, rowText: { flex: 1, color: "#14211F", fontSize: 15, lineHeight: 21, fontWeight: "700" }, rowTextDone: { color: "#457060", textDecorationLine: "line-through" }, footer: { marginTop: 24, borderRadius: 20, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E0E7E3", padding: 16 }, footerTop: { flexDirection: "row", alignItems: "center", gap: 8 }, footerTitle: { fontSize: 14, fontWeight: "800", color: "#14211F" }, footerText: { fontSize: 13, lineHeight: 19, color: "#5E706B", marginTop: 7 }, pressed: { opacity: 0.78, transform: [{ scale: 0.985 }] } });
