import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { BrandIcon } from "@/components/brand-assets";
import { AppButton } from "@/components/ui/app-button";
import { ScreenBack } from "@/components/screen-back";
import { ScreenContainer } from "@/components/screen-container";
import { type ExpenseCategory, type IncomeCategory, type TransactionCategory, useBusinessStore } from "@/lib/business-store";
import { useThemeContext } from "@/lib/theme-provider";

export default function AddTransactionScreen() {
  const { kind } = useLocalSearchParams<{ kind?: "income" | "expense" }>(); const [type, setType] = useState<"income" | "expense">(kind === "expense" ? "expense" : "income"); const [category, setCategory] = useState<TransactionCategory>(kind === "expense" ? "Operasional" : "Penjualan"); const [amount, setAmount] = useState(""); const [note, setNote] = useState(""); const [error, setError] = useState(""); const { addTransaction } = useBusinessStore(); const { colorScheme } = useThemeContext(); const dark = colorScheme === "dark";
  function save() { const numeric = Number(amount.replace(/[^0-9]/g, "")); if (!Number.isFinite(numeric) || numeric <= 0) { setError("Masukkan nominal uang yang lebih dari nol."); return; } addTransaction(type, numeric, note, category); router.back(); }
  const categoryItems = type === "income" ? (["Penjualan", "Jasa", "Pesanan khusus", "Lainnya"] as IncomeCategory[]) : (["Bahan baku", "Operasional", "Pemasaran", "Lainnya"] as ExpenseCategory[]);
  return <ScreenContainer className="px-4 pt-2" edges={["top", "bottom", "left", "right"]}><KeyboardAvoidingView className="flex-1" behavior={Platform.OS === "ios" ? "padding" : undefined}><ScreenBack title="Tambah Catatan" /><View style={styles.info}><BrandIcon name="money" size={19} color="#2D6EAE" /><Text style={styles.infoText}>Catatan ini hanya tersimpan di perangkat Anda.</Text></View><Text style={[styles.label, dark && styles.textDark]}>Jenis transaksi</Text><View style={styles.types}><TypeCard label="Pemasukan" icon="transfer" selected={type === "income"} onPress={() => { setType("income"); setCategory("Penjualan"); }} /><TypeCard label="Pengeluaran" icon="money" selected={type === "expense"} onPress={() => { setType("expense"); setCategory("Operasional"); }} /></View><Text style={[styles.label, dark && styles.textDark]}>{type === "income" ? "Sumber pemasukan" : "Kategori pengeluaran"}</Text><View style={styles.categories}>{categoryItems.map((item) => <Pressable key={item} onPress={() => setCategory(item)} style={({ pressed }) => [styles.category, category === item && styles.categoryActive, pressed && styles.pressed]} accessibilityRole="radio" accessibilityState={{ selected: category === item }}><Text style={[styles.categoryText, category === item && styles.categoryTextActive]}>{item}</Text></Pressable>)}</View><Text style={[styles.label, dark && styles.textDark]}>Nominal</Text><View style={styles.amountBox}><Text style={styles.currency}>Rp</Text><TextInput value={amount} onChangeText={(value) => { setAmount(value.replace(/[^0-9]/g, "")); setError(""); }} keyboardType="numeric" placeholder="0" placeholderTextColor="#A2B0BA" style={styles.amountInput} returnKeyType="done" /></View>{error ? <Text style={styles.error}>{error}</Text> : null}<Text style={[styles.label, dark && styles.textDark]}>Keterangan</Text><TextInput value={note} onChangeText={setNote} placeholder={type === "income" ? "Contoh: jual 10 porsi" : "Contoh: belanja bahan"} placeholderTextColor="#A2B0BA" style={styles.noteInput} returnKeyType="done" /><AppButton label="Simpan catatan" icon="check" onPress={save} style={styles.save} /></KeyboardAvoidingView></ScreenContainer>;
}

function TypeCard({ label, icon, selected, onPress }: { label: string; icon: "transfer" | "money"; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.type, selected && styles.typeSelected, pressed && styles.pressed]} accessibilityRole="button"><BrandIcon name={icon} size={18} color={selected ? "#2D6EAE" : "#8293A2"} /><Text style={[styles.typeText, selected && styles.typeTextSelected]}>{label}</Text></Pressable>; }

const styles = StyleSheet.create({ info: { minHeight: 44, borderRadius: 13, backgroundColor: "#E6F3FA", paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 8 }, infoText: { color: "#55758E", fontSize: 11, fontWeight: "800" }, label: { color: "#344B62", fontSize: 13, fontWeight: "900", marginTop: 22, marginBottom: 8 }, types: { flexDirection: "row", gap: 9 }, type: { flex: 1, height: 48, borderRadius: 13, borderWidth: 1, borderColor: "#DFE7EC", backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 6 }, typeSelected: { borderColor: "#2D6EAE", backgroundColor: "#EEF8FC" }, typeText: { color: "#718392", fontSize: 12, fontWeight: "900" }, typeTextSelected: { color: "#2D6EAE" }, categories: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, category: { borderRadius: 12, borderWidth: 1, borderColor: "#DFE7EC", backgroundColor: "#FFFFFF", paddingHorizontal: 11, paddingVertical: 8 }, categoryActive: { borderColor: "#2D6EAE", backgroundColor: "#EEF8FC" }, categoryText: { color: "#718392", fontSize: 10, fontWeight: "800" }, categoryTextActive: { color: "#2D6EAE" }, amountBox: { height: 62, borderRadius: 16, borderWidth: 1, borderColor: "#DFE7EC", backgroundColor: "#FFFFFF", paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 9 }, currency: { color: "#2D6EAE", fontSize: 19, fontWeight: "900" }, amountInput: { flex: 1, color: "#29435B", fontSize: 22, fontWeight: "900", paddingVertical: 12, fontVariant: ["tabular-nums"] }, noteInput: { height: 52, borderRadius: 14, borderWidth: 1, borderColor: "#DFE7EC", backgroundColor: "#FFFFFF", paddingHorizontal: 14, color: "#29435B", fontSize: 15 }, error: { color: "#B34A5A", fontSize: 11, fontWeight: "800", marginTop: 7 }, save: { marginTop: "auto", marginBottom: 8 }, textDark: { color: "#FFFFFF" }, pressed: { opacity: 0.8, transform: [{ scale: 0.985 }] } });
