import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useState } from "react";
import { BrandIcon } from "@/components/brand-assets";
import { AppButton } from "@/components/ui/app-button";
import { ScreenBack } from "@/components/screen-back";
import { ScreenContainer } from "@/components/screen-container";
import { type ExpenseCategory, useBusinessStore } from "@/lib/business-store";
import { formatRupiah } from "@/lib/business-utils";
import { useThemeContext } from "@/lib/theme-provider";

const categories: ExpenseCategory[] = ["Bahan baku", "Operasional", "Pemasaran", "Lainnya"];
export default function BudgetScreen() { const { budgets, setBudget } = useBusinessStore(); const { colorScheme } = useThemeContext(); const dark = colorScheme === "dark"; const [selected, setSelected] = useState<ExpenseCategory>("Operasional"); const [amount, setAmount] = useState(budgets.Operasional ? String(budgets.Operasional) : ""); const choose = (category: ExpenseCategory) => { setSelected(category); setAmount(budgets[category] ? String(budgets[category]) : ""); }; const save = () => setBudget(selected, Number(amount.replace(/[^0-9]/g, "")) || 0); return <ScreenContainer className="px-4 pt-2" edges={["top", "bottom", "left", "right"]}><ScreenBack title="Anggaran Pengeluaran" /><View style={styles.hero}><View style={styles.heroIcon}><BrandIcon name="money" size={24} color="#5E315D" /></View><Text style={styles.heroTitle}>Tetapkan batas untuk tiap kategori pengeluaran.</Text><Text style={styles.heroText}>UMKM KU akan membandingkan catatan bulan berjalan dengan batas anggaran Anda.</Text></View><Text style={[styles.heading, dark && styles.textDark]}>Pilih kategori</Text><View style={styles.categories}>{categories.map((category) => <Pressable key={category} onPress={() => choose(category)} style={({ pressed }) => [styles.category, selected === category && styles.categoryActive, pressed && styles.pressed]} accessibilityRole="radio" accessibilityState={{ selected: selected === category }}><Text style={[styles.categoryText, selected === category && styles.categoryTextActive]}>{category}</Text><Text style={[styles.categoryMeta, selected === category && styles.categoryMetaActive]}>{budgets[category] ? formatRupiah(budgets[category]!) : "Belum diatur"}</Text></Pressable>)}</View><Text style={[styles.heading, dark && styles.textDark]}>Batas {selected.toLowerCase()} per bulan</Text><View style={styles.inputRow}><Text style={styles.currency}>Rp</Text><TextInput value={amount} onChangeText={(value) => setAmount(value.replace(/[^0-9]/g, ""))} placeholder="0" keyboardType="numeric" style={styles.input} placeholderTextColor="#B0A1A0" /></View><Text style={[styles.hint, dark && styles.textDark]}>Masukkan 0 untuk menghapus batas pada kategori ini.</Text><AppButton label="Simpan anggaran" icon="check" onPress={save} style={styles.save} /></ScreenContainer>; }
const styles = StyleSheet.create({ hero: { borderRadius: 18, backgroundColor: "#FFF0D6", padding: 16 }, heroIcon: { width: 44, height: 44, borderRadius: 16, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" }, heroTitle: { color: "#3A1F3D", fontSize: 17, lineHeight: 23, fontWeight: "900", marginTop: 12 }, heroText: { color: "#7E6D72", fontSize: 12, lineHeight: 18, marginTop: 5 }, heading: { color: "#3A1F3D", fontSize: 14, fontWeight: "900", marginTop: 22, marginBottom: 8 }, categories: { gap: 8 }, category: { minHeight: 50, borderRadius: 14, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#F0E5D4", paddingHorizontal: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, categoryActive: { borderColor: "#F0B93D", backgroundColor: "#FFF8EE", borderWidth: 2 }, categoryText: { color: "#3A1F3D", fontSize: 12, fontWeight: "900" }, categoryTextActive: { color: "#5E315D" }, categoryMeta: { color: "#927F85", fontSize: 10, fontWeight: "800" }, categoryMetaActive: { color: "#986018" }, inputRow: { height: 62, borderRadius: 16, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#F0E5D4", paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 8 }, currency: { color: "#5E315D", fontSize: 19, fontWeight: "900" }, input: { flex: 1, color: "#3A1F3D", fontSize: 22, fontWeight: "900" }, hint: { color: "#927F85", fontSize: 10, lineHeight: 15, marginTop: 7 }, save: { marginTop: "auto", marginBottom: 8 }, textDark: { color: "#FFFFFF" }, pressed: { opacity: 0.8, transform: [{ scale: 0.985 }] } });
