import * as FileSystem from "expo-file-system/legacy";
import * as ImagePicker from "expo-image-picker";
import { Image, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useEffect, useState } from "react";
import { router } from "expo-router";

import { BrandIcon } from "@/components/brand-assets";
import { AppButton } from "@/components/ui/app-button";
import { ScreenBack } from "@/components/screen-back";
import { ScreenContainer } from "@/components/screen-container";
import { useBusinessStore } from "@/lib/business-store";
import { useThemeContext } from "@/lib/theme-provider";

export default function BusinessProfileScreen() {
  const { profile, saveProfile } = useBusinessStore();
  const { colorScheme } = useThemeContext();
  const dark = colorScheme === "dark";
  const [businessName, setBusinessName] = useState(profile.businessName); const [ownerName, setOwnerName] = useState(profile.ownerName); const [logoUri, setLogoUri] = useState<string | null>(profile.logoUri); const [saving, setSaving] = useState(false);
  useEffect(() => { setBusinessName(profile.businessName); setOwnerName(profile.ownerName); setLogoUri(profile.logoUri); }, [profile]);
  const chooseLogo = async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ImagePicker.MediaTypeOptions.Images, allowsEditing: true, aspect: [1, 1], quality: 0.85 }); if (result.canceled) return; setSaving(true); try { const source = result.assets[0]; if (Platform.OS === "web") { setLogoUri(source.uri); return; } const extension = source.fileName?.split(".").pop() ?? "jpg"; const target = `${FileSystem.documentDirectory}umkm-ku-business-logo.${extension}`; await FileSystem.copyAsync({ from: source.uri, to: target }); setLogoUri(target); } finally { setSaving(false); } };
  const save = () => { saveProfile({ businessName: businessName.trim() || "Usaha Anda", ownerName: ownerName.trim() || "Pemilik usaha", logoUri }); router.back(); };
  return <ScreenContainer className="px-4 pt-2" edges={["top", "bottom", "left", "right"]}><ScreenBack title="Identitas Usaha" /><View style={styles.hero}><View style={styles.heroIcon}><BrandIcon name="capital" size={24} color="#5E315D" /></View><Text style={styles.heroTitle}>Identitas ini akan muncul pada header laporan PDF.</Text><Text style={styles.heroText}>Semua data dan logo disimpan di perangkat Anda.</Text></View><Text style={[styles.label, dark && styles.textDark]}>Logo usaha</Text><View style={styles.logoRow}>{logoUri ? <Image source={{ uri: logoUri }} style={styles.logo} resizeMode="contain" /> : <View style={styles.logoEmpty}><BrandIcon name="capital" size={26} color="#B47A17" /></View>}<View className="flex-1"><Text style={styles.logoTitle}>{logoUri ? "Logo siap digunakan" : "Belum ada logo"}</Text><Text style={styles.logoText}>Gunakan gambar persegi agar terlihat rapi pada PDF.</Text><Pressable onPress={chooseLogo} style={({ pressed }) => [styles.logoAction, pressed && styles.pressed]} accessibilityRole="button"><Text style={styles.logoActionText}>{saving ? "Menyimpan…" : logoUri ? "Ganti logo" : "Unggah logo"}</Text></Pressable>{logoUri ? <Pressable onPress={() => setLogoUri(null)} style={({ pressed }) => [styles.remove, pressed && styles.pressed]} accessibilityRole="button"><Text style={styles.removeText}>Hapus logo</Text></Pressable> : null}</View></View><Text style={[styles.label, dark && styles.textDark]}>Nama usaha</Text><TextInput value={businessName} onChangeText={setBusinessName} placeholder="Contoh: Warung Gado-Gado Barokah" placeholderTextColor="#AA9A9A" style={styles.input} returnKeyType="next" /><Text style={[styles.label, dark && styles.textDark]}>Nama pemilik</Text><TextInput value={ownerName} onChangeText={setOwnerName} placeholder="Contoh: Budi Santoso" placeholderTextColor="#AA9A9A" style={styles.input} returnKeyType="done" /><AppButton label="Simpan identitas usaha" icon="check" onPress={save} style={styles.save} /></ScreenContainer>;
}

const styles = StyleSheet.create({ hero: { borderRadius: 18, backgroundColor: "#FFF0D6", padding: 16 }, heroIcon: { width: 44, height: 44, borderRadius: 16, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" }, heroTitle: { color: "#3A1F3D", fontSize: 17, lineHeight: 23, fontWeight: "900", marginTop: 12 }, heroText: { color: "#7E6D72", fontSize: 12, lineHeight: 18, marginTop: 5 }, label: { color: "#3A1F3D", fontSize: 13, fontWeight: "900", marginTop: 22, marginBottom: 8 }, logoRow: { minHeight: 108, borderRadius: 16, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#F0E5D4", padding: 12, flexDirection: "row", gap: 12 }, logo: { width: 80, height: 80, borderRadius: 15, backgroundColor: "#FFF8EE" }, logoEmpty: { width: 80, height: 80, borderRadius: 15, backgroundColor: "#FFF8EE", alignItems: "center", justifyContent: "center" }, logoTitle: { color: "#3A1F3D", fontSize: 12, fontWeight: "900" }, logoText: { color: "#7E6D72", fontSize: 9, lineHeight: 13, marginTop: 4 }, logoAction: { alignSelf: "flex-start", minHeight: 29, paddingHorizontal: 9, borderRadius: 10, backgroundColor: "#FFF0D6", alignItems: "center", justifyContent: "center", marginTop: 7 }, logoActionText: { color: "#5E315D", fontSize: 9, fontWeight: "900" }, remove: { alignSelf: "flex-start", marginTop: 4 }, removeText: { color: "#B34A5A", fontSize: 9, fontWeight: "900" }, input: { height: 52, borderRadius: 14, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#F0E5D4", paddingHorizontal: 13, color: "#3A1F3D", fontSize: 14, fontWeight: "700" }, save: { marginTop: "auto", marginBottom: 8 }, textDark: { color: "#FFFFFF" }, pressed: { opacity: 0.8, transform: [{ scale: 0.985 }] } });
