import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";
import { router } from "expo-router";
import { Platform, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useState } from "react";
import { BrandIcon } from "@/components/brand-assets";
import { AppButton } from "@/components/ui/app-button";
import { ScreenBack } from "@/components/screen-back";
import { ScreenContainer } from "@/components/screen-container";
import { useBusinessStore } from "@/lib/business-store";
import { formatRupiah } from "@/lib/business-utils";
import { trpc } from "@/lib/trpc";
import { useThemeContext } from "@/lib/theme-provider";

type ImportedTransaction = { type: "income" | "expense"; amount: number; note: string; category: "Penjualan" | "Operasional"; date: string };
export default function ImportPdfScreen() {
  const { importTransactions } = useBusinessStore(); const parser = trpc.financeImport.parsePdf.useMutation(); const { colorScheme } = useThemeContext(); const dark = colorScheme === "dark"; const [preview, setPreview] = useState<{ reportName: string; periodLabel: string; transactions: ImportedTransaction[] } | null>(null); const [message, setMessage] = useState("");
  const readWebFile = async (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1] ?? ""); reader.onerror = reject; reader.readAsDataURL(file); });
  const choose = async () => { setMessage(""); try { const result = await DocumentPicker.getDocumentAsync({ type: "application/pdf", copyToCacheDirectory: true }); if (result.canceled) return; const asset = result.assets[0]; setMessage("Membaca format laporan..."); const base64 = Platform.OS === "web" && asset.file ? await readWebFile(asset.file as File) : await FileSystem.readAsStringAsync(asset.uri, { encoding: FileSystem.EncodingType.Base64 }); const parsed = await parser.mutateAsync({ base64, fileName: asset.name ?? "Laporan PDF" }); setPreview(parsed); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "PDF belum dapat dibaca. Pastikan memakai template Laporan Keuangan UMKM-KU."); } };
  const confirm = () => { if (!preview) return; importTransactions(preview.transactions); router.replace("/(tabs)/money"); };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.content}><ScreenBack title="Impor Laporan PDF" /><View style={styles.hero}><View style={styles.heroIcon}><BrandIcon name="money" size={25} color="#5E315D" /></View><Text style={styles.heroTitle}>Masukkan riwayat tanpa ketik ulang.</Text><Text style={styles.heroText}>UMKM KU membaca total pemasukan dan pengeluaran dari template Laporan Keuangan UMKM-KU, lalu menampilkannya untuk Anda konfirmasi.</Text></View>{!preview ? <><AppButton label={parser.isPending ? "Membaca PDF..." : "Pilih laporan PDF"} icon="share" onPress={choose} style={styles.choose} /><Text style={[styles.templateTitle, dark && styles.textDark]}>Format yang didukung</Text><View style={styles.template}><Text style={styles.templateText}>Laporan Keuangan Harian UMKM-KU dengan kolom total pemasukan, total pengeluaran, dan periode laporan.</Text></View>{message ? <View style={styles.message}><Text style={styles.messageText}>{message}</Text></View> : null}</> : <><View style={styles.previewHead}><Text style={styles.previewLabel}>PRATINJAU IMPOR</Text><Text style={styles.previewPeriod}>{preview.periodLabel}</Text><Text style={styles.previewName}>{preview.reportName}</Text></View><View style={styles.items}>{preview.transactions.map((item) => <View key={item.type} style={styles.item}><View style={[styles.itemIcon, item.type === "income" ? styles.incomeIcon : styles.expenseIcon]}><BrandIcon name="money" size={17} color={item.type === "income" ? "#2E8C67" : "#B34A5A"} /></View><View className="flex-1"><Text style={styles.itemTitle}>{item.type === "income" ? "Pemasukan" : "Pengeluaran"}</Text><Text style={styles.itemMeta}>{item.category} · {new Date(item.date).toLocaleDateString("id-ID")}</Text></View><Text style={[styles.itemValue, { color: item.type === "income" ? "#2E8C67" : "#B34A5A" }]}>{item.type === "income" ? "+" : "−"}{formatRupiah(item.amount)}</Text></View>)}</View><Text style={[styles.notice, dark && styles.textDark]}>Catatan impor akan ditambahkan ke pembukuan sebagai ringkasan total dari periode laporan. Periksa nominal sebelum melanjutkan.</Text><AppButton label="Konfirmasi dan impor" icon="check" onPress={confirm} style={styles.confirm} /><Pressable onPress={() => { setPreview(null); void choose(); }} style={({ pressed }) => [styles.change, pressed && styles.pressed]} accessibilityRole="button"><Text style={[styles.changeText, dark && styles.textDark]}>Pilih PDF lain</Text></Pressable></>}</ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 16, paddingTop: 8, paddingBottom: 32 }, hero: { borderRadius: 18, backgroundColor: "#FFF0D6", padding: 16, marginTop: 12 }, heroIcon: { width: 44, height: 44, borderRadius: 16, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" }, heroTitle: { color: "#3A1F3D", fontSize: 18, lineHeight: 24, fontWeight: "900", marginTop: 12 }, heroText: { color: "#7E6D72", fontSize: 12, lineHeight: 18, marginTop: 5 }, choose: { marginTop: 18 }, templateTitle: { color: "#3A1F3D", fontSize: 13, fontWeight: "900", marginTop: 22, marginBottom: 8 }, template: { borderRadius: 14, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#F0E5D4", padding: 12 }, templateText: { color: "#7E6D72", fontSize: 10, lineHeight: 15 }, message: { marginTop: 12, borderRadius: 13, backgroundColor: "#FCE8EB", padding: 11 }, messageText: { color: "#A44555", fontSize: 10, lineHeight: 15, fontWeight: "700" }, previewHead: { marginTop: 18, borderRadius: 15, backgroundColor: "#5E315D", padding: 14 }, previewLabel: { color: "#F8D98C", fontSize: 9, fontWeight: "900", letterSpacing: 0.6 }, previewPeriod: { color: "#FFFFFF", fontSize: 16, fontWeight: "900", marginTop: 5 }, previewName: { color: "#FFFFFF", fontSize: 10, marginTop: 4 }, items: { marginTop: 10, gap: 8 }, item: { minHeight: 65, borderRadius: 14, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#F0E5D4", paddingHorizontal: 11, flexDirection: "row", alignItems: "center", gap: 9 }, itemIcon: { width: 34, height: 34, borderRadius: 12, alignItems: "center", justifyContent: "center" }, incomeIcon: { backgroundColor: "#E8F3E5" }, expenseIcon: { backgroundColor: "#FCE8EB" }, itemTitle: { color: "#3A1F3D", fontSize: 12, fontWeight: "900" }, itemMeta: { color: "#927F85", fontSize: 9, marginTop: 3 }, itemValue: { fontSize: 12, fontWeight: "900" }, notice: { color: "#7E6D72", fontSize: 10, lineHeight: 15, marginTop: 12 }, confirm: { marginTop: 18 }, change: { alignSelf: "center", marginTop: 13, minHeight: 35, justifyContent: "center" }, changeText: { color: "#5E315D", fontSize: 11, fontWeight: "900" }, textDark: { color: "#FFFFFF" }, pressed: { opacity: 0.8, transform: [{ scale: 0.985 }] } });
