import { LayoutAnimation, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { router } from "expo-router";
import { BrandIcon, type BrandIconName } from "@/components/brand-assets";
import { ScreenBack } from "@/components/screen-back";
import { ScreenContainer } from "@/components/screen-container";
import { type KabarCategory } from "@/lib/kabar-content";
import { useBusinessStore } from "@/lib/business-store";
import { useOnboarding } from "@/lib/onboarding-provider";
import { type TextSize, useThemeContext } from "@/lib/theme-provider";

const interests: { category: KabarCategory; title: string; text: string; icon: BrandIconName; tint: string; color: string }[] = [
  { category: "Legalitas", title: "Legalitas usaha", text: "Izin, merek, dan dokumen usaha", icon: "permit", tint: "#E6F3FA", color: "#2D6EAE" },
  { category: "Modal", title: "Modal & pertumbuhan", text: "Kesiapan modal dan pengembangan usaha", icon: "capital", tint: "#E9F1FA", color: "#386E9F" },
  { category: "Pelatihan", title: "Pelatihan", text: "Materi pemasaran dan pengelolaan usaha", icon: "academy", tint: "#EFEAFE", color: "#5E4BB7" },
  { category: "Pembukuan", title: "Pembukuan", text: "Kebiasaan catat uang dan arus kas", icon: "money", tint: "#E8F3E5", color: "#2E8C67" },
];
const sizes: { id: TextSize; label: string; fontSize: number }[] = [{ id: "small", label: "Kecil", fontSize: 15 }, { id: "medium", label: "Sedang", fontSize: 18 }, { id: "large", label: "Besar", fontSize: 21 }];

export default function PreferencesScreen() {
  const { interests: selected, toggleInterest, profile } = useBusinessStore();
  const { colorScheme, setColorScheme, textSize, setTextSize, celebrationsEnabled, setCelebrationsEnabled } = useThemeContext();
  const { restartTour } = useOnboarding();
  const dark = colorScheme === "dark";
  const animate = (action: () => void) => { LayoutAnimation.configureNext({ duration: 220, update: { type: "easeInEaseOut" } }); action(); };

  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={s.content}>
    <ScreenBack title="Pengaturan Kabar" />
    <View style={[s.hero, dark && s.heroDark]}><View style={[s.heroIcon, dark && s.cardDark]}><BrandIcon name="bell" size={23} color="#2D6EAE" /></View><Text style={[s.heroTitle, dark && s.textDark]}>Atur tampilan dan kabar sesuai kenyamanan Anda.</Text><Text style={[s.heroText, dark && s.mutedDark]}>Pilihan tema, teks, dan minat tersimpan di perangkat.</Text></View>
    <Text style={[s.heading, dark && s.textDark]}>Profil laporan</Text><Row title={profile.businessName} text={`${profile.ownerName} · Nama & logo untuk PDF`} icon="capital" onPress={() => router.push("/business-profile")} dark={dark} />
    <Text style={[s.heading, dark && s.textDark]}>Tampilan aplikasi</Text><View style={s.themeRow}>{(["light", "dark"] as const).map((scheme) => <Pressable key={scheme} onPress={() => animate(() => setColorScheme(scheme))} style={({ pressed }) => [s.theme, dark && s.cardDark, colorScheme === scheme && s.active, dark && colorScheme === scheme && s.activeDark, pressed && s.pressed]}><View style={[s.mini, scheme === "dark" && s.miniDark]} /><Text style={[s.cardTitle, dark && s.textDark]}>{scheme === "light" ? "Light" : "Dark"}</Text><Text style={[s.cardText, dark && s.mutedDark]}>{scheme === "light" ? "Putih bersih" : "Navy nyaman"}</Text></Pressable>)}</View>
    <Text style={[s.heading, dark && s.textDark]}>Ukuran teks artikel</Text><View style={s.sizeRow}>{sizes.map((size) => <Pressable key={size.id} onPress={() => animate(() => setTextSize(size.id))} style={({ pressed }) => [s.size, dark && s.cardDark, textSize === size.id && s.active, dark && textSize === size.id && s.activeDark, pressed && s.pressed]}><Text style={[s.sizeSample, { fontSize: size.fontSize }, dark && s.textDark]}>Aa</Text><Text style={[s.cardText, dark && s.mutedDark]}>{size.label}</Text></Pressable>)}</View>
    <Text style={[s.heading, dark && s.textDark]}>Efek aplikasi</Text><View style={[s.row, dark && s.cardDark]}><View style={s.rowIcon}><BrandIcon name="activity" size={21} color="#2D6EAE" /></View><View style={s.grow}><Text style={[s.cardTitle, dark && s.textDark]}>Animasi confetti</Text><Text style={[s.cardText, dark && s.mutedDark]}>Tampilkan selebrasi saat kartu lencana tersimpan.</Text></View><Switch value={celebrationsEnabled} onValueChange={setCelebrationsEnabled} trackColor={{ false: "#C9D3DA", true: "#9DCAE5" }} thumbColor={celebrationsEnabled ? "#2D6EAE" : "#F7F9FA"} /></View>
    <Text style={[s.heading, dark && s.textDark]}>Bantuan awal</Text><Row title="Ulangi tutorial aplikasi" text="Lihat kembali urutan langkah penting untuk usaha Anda." icon="guide" onPress={restartTour} dark={dark} />
    <Text style={[s.heading, dark && s.textDark]}>Pilih minat Anda</Text>{interests.map((choice) => <Pressable key={choice.category} onPress={() => toggleInterest(choice.category)} style={({ pressed }) => [s.row, dark && s.cardDark, selected.includes(choice.category) && s.active, pressed && s.pressed]}><View style={[s.rowIcon, { backgroundColor: choice.tint }]}><BrandIcon name={choice.icon} size={21} color={choice.color} /></View><View style={s.grow}><Text style={[s.cardTitle, dark && s.textDark]}>{choice.title}</Text><Text style={[s.cardText, dark && s.mutedDark]}>{choice.text}</Text></View><Text style={s.select}>{selected.includes(choice.category) ? "✓" : ""}</Text></Pressable>)}</ScrollView></ScreenContainer>;
}
function Row({ title, text, icon, onPress, dark }: { title: string; text: string; icon: BrandIconName; onPress: () => void; dark: boolean }) { return <Pressable onPress={onPress} style={({ pressed }) => [s.row, dark && s.cardDark, pressed && s.pressed]}><View style={s.rowIcon}><BrandIcon name={icon} size={21} color="#2D6EAE" /></View><View style={s.grow}><Text style={[s.cardTitle, dark && s.textDark]}>{title}</Text><Text style={[s.cardText, dark && s.mutedDark]}>{text}</Text></View><BrandIcon name="arrow" size={18} color="#2D6EAE" /></Pressable>; }
const s = StyleSheet.create({ content: { padding: 16, paddingTop: 8, paddingBottom: 34 }, grow: { flex: 1 }, hero: { borderRadius: 18, backgroundColor: "#F4F8FB", borderWidth: 1, borderColor: "#E2E9ED", padding: 16 }, heroDark: { backgroundColor: "#222C40", borderColor: "#222C40" }, heroIcon: { width: 42, height: 42, borderRadius: 15, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" }, heroTitle: { color: "#29435B", fontSize: 17, lineHeight: 22, fontWeight: "900", marginTop: 12 }, heroText: { color: "#718292", fontSize: 12, lineHeight: 18, marginTop: 5 }, heading: { color: "#29435B", fontSize: 15, fontWeight: "900", marginTop: 22, marginBottom: 9 }, row: { minHeight: 67, backgroundColor: "#FFFFFF", borderRadius: 15, borderWidth: 1, borderColor: "#E2E9ED", padding: 10, flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 9 }, rowIcon: { width: 38, height: 38, borderRadius: 13, backgroundColor: "#E6F3FA", alignItems: "center", justifyContent: "center" }, themeRow: { flexDirection: "row", gap: 9 }, theme: { flex: 1, minHeight: 116, borderRadius: 16, borderWidth: 1, borderColor: "#E2E9ED", backgroundColor: "#FFFFFF", padding: 10 }, mini: { height: 52, borderRadius: 10, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E2E9ED" }, miniDark: { backgroundColor: "#101827", borderColor: "#26344B" }, sizeRow: { flexDirection: "row", gap: 8 }, size: { flex: 1, height: 70, borderRadius: 15, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E2E9ED", alignItems: "center", justifyContent: "center" }, active: { borderColor: "#2D6EAE", borderWidth: 2, backgroundColor: "#F4F8FB" }, activeDark: { backgroundColor: "#172235" }, cardDark: { backgroundColor: "#172235", borderColor: "#2A3B54" }, cardTitle: { color: "#29435B", fontSize: 12, fontWeight: "900", marginTop: 5 }, cardText: { color: "#718292", fontSize: 9, lineHeight: 13, marginTop: 3 }, sizeSample: { color: "#29435B", fontWeight: "900" }, select: { color: "#2D6EAE", fontSize: 18, fontWeight: "900" }, textDark: { color: "#FFFFFF" }, mutedDark: { color: "#FFFFFF" }, pressed: { opacity: .8, transform: [{ scale: .985 }] } });
