import { router } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

import { BrandIcon } from "@/components/brand-assets";
import { ScreenBack } from "@/components/screen-back";
import { ScreenContainer } from "@/components/screen-container";
import { readinessQuestions, type ReadinessKey } from "@/lib/business-content";
import { useBusinessStore } from "@/lib/business-store";
import { useThemeContext } from "@/lib/theme-provider";

export default function ReadinessScreen() {
  const { readiness, saveReadiness } = useBusinessStore();
  const { colorScheme } = useThemeContext();
  const dark = colorScheme === "dark";
  const [index, setIndex] = useState(0); const [answers, setAnswers] = useState(() => ({ ...readiness }));
  const current = readinessQuestions[index]; const selected = answers[current.id]; const progress = useMemo(() => ((index + 1) / readinessQuestions.length) * 100, [index]);
  function choose(answer: boolean) { const next = { ...answers, [current.id]: answer }; setAnswers(next); if (index === readinessQuestions.length - 1) { saveReadiness(next as Record<ReadinessKey, boolean | null>); router.replace("/readiness-result"); } else setIndex((value) => value + 1); }
  return <ScreenContainer className="px-4 pt-2" edges={["top", "bottom", "left", "right"]}><ScreenBack title="Cek Kesiapan" /><View style={styles.stepRow}><Text style={[styles.stepLabel, dark && styles.textDark]}>LANGKAH {index + 1} DARI {readinessQuestions.length}</Text><Text style={styles.percent}>{Math.round(progress)}%</Text></View><View style={styles.track}><View style={[styles.value, { width: `${progress}%` }]} /></View><View style={styles.questionArea}><View style={styles.iconShell}><BrandIcon name="guide" size={27} color="#2D6EAE" /></View><Text style={[styles.question, dark && styles.textDark]}>{current.question}</Text><Text style={[styles.help, dark && styles.textDark]}>{current.help}</Text></View><View style={styles.choices}><Choice label="Sudah, saya siap" text="Bagus, lanjut ke pertanyaan berikutnya." selected={selected === true} onPress={() => choose(true)} /><Choice label="Belum" text="Tidak apa-apa, nanti ada langkah yang bisa diikuti." selected={selected === false} onPress={() => choose(false)} /></View><Text style={[styles.privacy, dark && styles.textDark]}>Jawaban ini hanya dipakai untuk rekomendasi di perangkat Anda.</Text></ScreenContainer>;
}

function Choice({ label, text, selected, onPress }: { label: string; text: string; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.choice, selected && styles.choiceSelected, pressed && styles.pressed]} accessibilityRole="button"><View className="flex-1"><Text style={[styles.choiceTitle, selected && styles.choiceTitleSelected]}>{label}</Text><Text style={styles.choiceText}>{text}</Text></View><View style={[styles.radio, selected && styles.radioSelected]}>{selected ? <Text style={styles.radioTick}>✓</Text> : null}</View></Pressable>; }

const styles = StyleSheet.create({ stepRow: { flexDirection: "row", justifyContent: "space-between", marginTop: 2 }, stepLabel: { color: "#738A9B", fontSize: 10, fontWeight: "900", letterSpacing: 0.8 }, percent: { color: "#2D6EAE", fontSize: 12, fontWeight: "900" }, track: { height: 7, backgroundColor: "#DFE8EE", borderRadius: 7, overflow: "hidden", marginTop: 9 }, value: { height: 7, backgroundColor: "#2D6EAE", borderRadius: 7 }, questionArea: { flex: 1, paddingTop: 43 }, iconShell: { width: 50, height: 50, borderRadius: 17, backgroundColor: "#E6F3FA", alignItems: "center", justifyContent: "center" }, question: { color: "#29435B", fontSize: 27, lineHeight: 34, fontWeight: "900", marginTop: 18, letterSpacing: -0.3 }, help: { color: "#718392", fontSize: 15, lineHeight: 22, marginTop: 9 }, choices: { gap: 10, marginBottom: 18 }, choice: { minHeight: 78, borderRadius: 16, borderWidth: 1, borderColor: "#DCE6ED", backgroundColor: "#FFFFFF", padding: 15, flexDirection: "row", alignItems: "center", gap: 12 }, choiceSelected: { borderColor: "#2D6EAE", backgroundColor: "#EDF7FC" }, choiceTitle: { color: "#344B62", fontSize: 15, fontWeight: "900" }, choiceTitleSelected: { color: "#2D6EAE" }, choiceText: { color: "#8293A2", fontSize: 11, lineHeight: 16, marginTop: 3 }, radio: { width: 26, height: 26, borderRadius: 13, borderWidth: 1.5, borderColor: "#AABAC5", alignItems: "center", justifyContent: "center" }, radioSelected: { borderColor: "#2D6EAE", backgroundColor: "#2D6EAE" }, radioTick: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" }, privacy: { color: "#8293A2", fontSize: 11, lineHeight: 16, textAlign: "center", marginBottom: 8 }, textDark: { color: "#FFFFFF" }, pressed: { opacity: 0.8, transform: [{ scale: 0.985 }] } });
