import AsyncStorage from "@react-native-async-storage/async-storage";
import { useEffect, useState } from "react";
import { Modal, Pressable, StyleSheet, Text, View } from "react-native";
import { BrandIcon, type BrandIconName } from "@/components/brand-assets";
import { useBusinessStore } from "@/lib/business-store";
import { useThemeContext } from "@/lib/theme-provider";
const REWARD_KEY = "umkm-ku-milestones-seen";
type Reward = { id: "profile" | "first-transaction"; icon: BrandIconName; eyebrow: string; title: string; text: string };
const rewards: Reward[] = [{ id: "profile", icon: "capital", eyebrow: "LANGKAH PENTING SELESAI", title: "Profil usaha siap digunakan", text: "Nama usaha dan pemilik sudah siap tampil pada laporan PDF. Anda mendapat lencana: Usaha Teridentifikasi." }, { id: "first-transaction", icon: "money", eyebrow: "CATATAN PERTAMA BERHASIL", title: "Pembukuan Anda dimulai", text: "Transaksi pertama telah tercatat. Teruskan kebiasaan ini agar arus kas usaha selalu mudah dipantau." }];
export function MilestoneRewards() { const { profile, transactions, hydrated } = useBusinessStore(); const { colorScheme } = useThemeContext(); const dark = colorScheme === "dark"; const [seen, setSeen] = useState<string[]>([]); const [loaded, setLoaded] = useState(false); const [active, setActive] = useState<Reward | null>(null); useEffect(() => { void AsyncStorage.getItem(REWARD_KEY).then((value) => { setSeen(value ? JSON.parse(value) : []); setLoaded(true); }).catch(() => setLoaded(true)); }, []); useEffect(() => { if (!loaded || !hydrated || active) return; const profileReady = profile.businessName !== "Usaha Anda" && profile.ownerName !== "Pemilik usaha"; const transactionReady = transactions.length > 0; const next = rewards.find((reward) => !seen.includes(reward.id) && (reward.id === "profile" ? profileReady : transactionReady)); if (next) setActive(next); }, [active, hydrated, loaded, profile.businessName, profile.ownerName, seen, transactions.length]); const close = () => { if (!active) return; const nextSeen = [...seen, active.id]; setSeen(nextSeen); setActive(null); void AsyncStorage.setItem(REWARD_KEY, JSON.stringify(nextSeen)); }; return <Modal visible={Boolean(active)} transparent animationType="fade" onRequestClose={close}><View style={styles.backdrop}><View style={[styles.card, dark && styles.cardDark]}><View style={styles.star}><BrandIcon name={active?.icon ?? "activity"} size={28} color="#2D6EAE" /></View><Text style={styles.eyebrow}>{active?.eyebrow}</Text><Text style={[styles.title, dark && styles.textDark]}>{active?.title}</Text><Text style={[styles.text, dark && styles.textDark]}>{active?.text}</Text><View style={[styles.badge, dark && styles.badgeDark]}><BrandIcon name="activity" size={15} color="#168B72" /><Text style={[styles.badgeText, dark && styles.textDark]}>Reward tersimpan untuk progres usaha Anda</Text></View><Pressable onPress={close} style={styles.button} accessibilityRole="button"><Text style={styles.buttonText}>Lanjutkan usaha saya</Text><BrandIcon name="arrow" size={16} color="#FFFFFF" /></Pressable></View></View></Modal>; }
const styles = StyleSheet.create({ backdrop: { flex: 1, justifyContent: "center", padding: 26, backgroundColor: "rgba(8, 18, 32, 0.58)" }, card: { borderRadius: 24, backgroundColor: "#FFFFFF", padding: 22, alignItems: "center" }, cardDark: { backgroundColor: "#172235", borderWidth: 1, borderColor: "#2A3B54" }, star: { width: 64, height: 64, borderRadius: 22, backgroundColor: "#E6F3FA", alignItems: "center", justifyContent: "center" }, eyebrow: { color: "#2D6EAE", fontSize: 10, fontWeight: "900", letterSpacing: 0.75, marginTop: 17, textAlign: "center" }, title: { color: "#29435B", fontSize: 21, lineHeight: 27, fontWeight: "900", marginTop: 5, textAlign: "center" }, text: { color: "#64778A", fontSize: 13, lineHeight: 19, marginTop: 8, textAlign: "center" }, badge: { flexDirection: "row", alignItems: "center", gap: 6, backgroundColor: "#E8F6F1", borderRadius: 10, paddingVertical: 8, paddingHorizontal: 10, marginTop: 16 }, badgeDark: { backgroundColor: "#223847" }, badgeText: { color: "#42766A", fontSize: 10, fontWeight: "800" }, button: { width: "100%", minHeight: 46, borderRadius: 14, backgroundColor: "#2D6EAE", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, marginTop: 18 }, buttonText: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" }, textDark: { color: "#FFFFFF" } });
