import type { BrandIconName } from "@/components/brand-assets";

export type KabarCategory = "Legalitas" | "Modal" | "Pelatihan" | "Pembukuan";
export type KabarItem = { id: string; kind: "news" | "opportunity"; category: KabarCategory; source: string; title: string; summary: string; body: string[]; takeaway: string; icon: BrandIconName; color: string; tint: string; sourceUrl?: string };

export const kabarItems: KabarItem[] = [
  { id: "oss", kind: "news", category: "Legalitas", source: "OSS Indonesia", title: "Siapkan klasifikasi usaha sebelum mengurus perizinan", summary: "Kenali kegiatan usaha dan dokumen dasar yang perlu disiapkan sebelum memulai proses perizinan.", takeaway: "Catat kegiatan utama usaha Anda sebelum mulai mengurus izin.", icon: "permit", color: "#2D6EAE", tint: "#E6F3FA", sourceUrl: "https://oss.go.id", body: ["Perizinan usaha akan lebih mudah dipahami ketika kegiatan utama usaha sudah dirumuskan dengan jelas. Mulailah dengan menuliskan produk atau jasa yang benar-benar Anda jual, cara menjualnya, dan siapa pelanggan utamanya.", "Setelah itu, siapkan informasi dasar secara rapi. Data pemilik usaha, alamat usaha, dan gambaran kegiatan usaha biasanya menjadi fondasi saat Anda melanjutkan ke proses legalitas.", "BantuUsaha menyarankan agar Anda tidak mengerjakan semua sekaligus. Pilih satu langkah hari ini: merangkum kegiatan utama usaha. Langkah kecil ini memudahkan Anda mencari panduan perizinan yang relevan." ] },
  { id: "academy", kind: "news", category: "Pelatihan", source: "SAPA UMKM", title: "Tingkatkan kapasitas usaha melalui pelatihan digital", summary: "Temukan pembelajaran untuk pemasaran, pengelolaan usaha, dan kesiapan bisnis Anda.", takeaway: "Pilih satu materi yang paling dekat dengan masalah usaha hari ini.", icon: "academy", color: "#5E4BB7", tint: "#EFEAFE", sourceUrl: "https://sapa.umkm.go.id/", body: ["Pelatihan yang tepat tidak harus panjang atau rumit. Materi singkat tentang foto produk, pencatatan uang, atau cara menulis deskripsi jualan dapat memberi dampak langsung pada kegiatan sehari-hari.", "Sebelum memilih kelas, tentukan masalah yang ingin Anda selesaikan. Misalnya, jika penjualan belum konsisten, fokus dulu pada materi pemasaran. Jika uang usaha bercampur dengan uang pribadi, mulai dari pembukuan sederhana.", "Setelah belajar, praktikkan satu hal yang paling mungkin dilakukan pada hari yang sama. Kebiasaan mencoba akan membantu materi berubah menjadi perbaikan nyata pada usaha." ] },
  { id: "capital", kind: "opportunity", category: "Modal", source: "Peluang Usaha", title: "Persiapkan usaha untuk peluang modal", summary: "Lengkapi catatan uang, kebutuhan modal, dan dokumen dasar agar usaha lebih siap berkembang.", takeaway: "Mulai dengan mengetahui kebutuhan modal dan kebiasaan pencatatan usaha Anda.", icon: "capital", color: "#986018", tint: "#FFF1D6", body: ["Peluang modal biasanya lebih mudah dijajaki ketika pemilik usaha memahami tujuan penggunaan dana. Bedakan kebutuhan modal kerja, pembelian alat, stok, atau pengembangan produk.", "Mulailah membuat daftar sederhana: berapa dana yang dibutuhkan, untuk apa dana digunakan, dan perubahan apa yang Anda harapkan setelah dana tersedia. Tidak perlu langsung membuat proposal panjang.", "Catatan pemasukan dan pengeluaran akan membantu Anda melihat kondisi usaha dengan lebih nyata. Gunakan pembukuan BantuUsaha untuk membangun kebiasaan sebelum mencari informasi pendanaan lebih lanjut." ] },
  { id: "brand", kind: "news", category: "Legalitas", source: "DJKI", title: "Lindungi nama dan identitas produk sejak awal", summary: "Pelajari pentingnya merek agar identitas usaha lebih mudah dikenali dan dilindungi.", takeaway: "Gunakan nama usaha yang konsisten di produk, media sosial, dan catatan pelanggan.", icon: "book", color: "#A84858", tint: "#FCE8EC", sourceUrl: "https://www.dgip.go.id/", body: ["Nama, logo, dan kemasan membantu pelanggan mengenali usaha Anda. Konsistensi pada elemen ini juga membuat komunikasi usaha terasa lebih profesional.", "Sebelum membuat banyak materi promosi, cek kembali apakah nama yang digunakan sudah sama di seluruh saluran. Catat variasi nama yang pernah dipakai agar Anda dapat memilih satu identitas yang paling tepat.", "Informasi resmi mengenai perlindungan merek dapat membantu Anda memahami langkah berikutnya. Gunakan sumber tepercaya sebelum mengirim dokumen atau melakukan pembayaran." ] },
  { id: "money", kind: "opportunity", category: "Pembukuan", source: "Peluang Usaha", title: "Bangun kebiasaan catat uang setiap hari", summary: "Catatan sederhana membantu Anda melihat arus pemasukan dan pengeluaran usaha dengan lebih jelas.", takeaway: "Catat satu transaksi pertama hari ini, lalu lanjutkan besok.", icon: "money", color: "#168B72", tint: "#E3F7F0", body: ["Pembukuan tidak harus dimulai dengan laporan yang rumit. Yang penting adalah membiasakan diri mencatat uang masuk dan uang keluar usaha secara konsisten.", "Gunakan keterangan singkat yang mudah Anda pahami, misalnya jual 10 porsi, belanja bahan, atau ongkir. Keterangan seperti ini akan membantu Anda membaca kembali transaksi pada akhir minggu.", "Saat catatan mulai terkumpul, Anda dapat melihat pola yang sebelumnya sulit diperhatikan. Dari situ, langkah kecil seperti mengatur stok atau menetapkan target penjualan menjadi lebih mudah dibuat." ] },
];

export function getKabarItem(id: string) { return kabarItems.find((item) => item.id === id); }
