import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { View } from "react-native";
import { colorScheme as nativewindColorScheme, vars } from "nativewind";
import { SchemeColors, type ColorScheme } from "@/constants/theme";

export type TextSize = "small" | "medium" | "large";
type ThemeContextValue = { colorScheme: ColorScheme; setColorScheme: (scheme: ColorScheme) => void; textSize: TextSize; textScale: number; setTextSize: (size: TextSize) => void; celebrationsEnabled: boolean; setCelebrationsEnabled: (enabled: boolean) => void };
const THEME_STORAGE_KEY = "bantuusaha-theme"; const TEXT_SIZE_STORAGE_KEY = "bantuusaha-text-size"; const CELEBRATIONS_STORAGE_KEY = "umkm-ku-celebrations-enabled"; const textScales: Record<TextSize, number> = { small: .9, medium: 1, large: 1.16 };
const ThemeContext = createContext<ThemeContextValue | null>(null);
export function ThemeProvider({ children }: { children: React.ReactNode }) { const [colorScheme, setColorSchemeState] = useState<ColorScheme>("light"); const [textSize, setTextSizeState] = useState<TextSize>("medium"); const [celebrationsEnabled, setCelebrationsEnabledState] = useState(true);
  const applyScheme = useCallback((scheme: ColorScheme) => { nativewindColorScheme.set(scheme); if (typeof document !== "undefined") { const root = document.documentElement; root.dataset.theme = scheme; root.classList.toggle("dark", scheme === "dark"); Object.entries(SchemeColors[scheme]).forEach(([token, value]) => root.style.setProperty(`--color-${token}`, value)); } }, []);
  const setColorScheme = useCallback((scheme: ColorScheme) => { setColorSchemeState(scheme); applyScheme(scheme); void AsyncStorage.setItem(THEME_STORAGE_KEY, scheme); }, [applyScheme]); const setTextSize = useCallback((size: TextSize) => { setTextSizeState(size); void AsyncStorage.setItem(TEXT_SIZE_STORAGE_KEY, size); }, []); const setCelebrationsEnabled = useCallback((enabled: boolean) => { setCelebrationsEnabledState(enabled); void AsyncStorage.setItem(CELEBRATIONS_STORAGE_KEY, enabled ? "true" : "false"); }, []);
  useEffect(() => { applyScheme(colorScheme); }, [applyScheme, colorScheme]); useEffect(() => { void AsyncStorage.getItem(THEME_STORAGE_KEY).then((saved) => { if (saved === "light" || saved === "dark") setColorSchemeState(saved); }); void AsyncStorage.getItem(TEXT_SIZE_STORAGE_KEY).then((saved) => { if (saved === "small" || saved === "medium" || saved === "large") setTextSizeState(saved); }); void AsyncStorage.getItem(CELEBRATIONS_STORAGE_KEY).then((saved) => { if (saved === "false") setCelebrationsEnabledState(false); }); }, []);
  const themeVariables = useMemo(() => vars({ "color-primary": SchemeColors[colorScheme].primary, "color-background": SchemeColors[colorScheme].background, "color-surface": SchemeColors[colorScheme].surface, "color-foreground": SchemeColors[colorScheme].foreground, "color-muted": SchemeColors[colorScheme].muted, "color-border": SchemeColors[colorScheme].border, "color-success": SchemeColors[colorScheme].success, "color-warning": SchemeColors[colorScheme].warning, "color-error": SchemeColors[colorScheme].error }), [colorScheme]);
  const value = useMemo(() => ({ colorScheme, setColorScheme, textSize, textScale: textScales[textSize], setTextSize, celebrationsEnabled, setCelebrationsEnabled }), [celebrationsEnabled, colorScheme, setCelebrationsEnabled, setColorScheme, setTextSize, textSize]); return <ThemeContext.Provider value={value}><View style={[{ flex: 1 }, themeVariables]}>{children}</View></ThemeContext.Provider>; }
export function useThemeContext(): ThemeContextValue { const ctx = useContext(ThemeContext); if (!ctx) throw new Error("useThemeContext must be used within ThemeProvider"); return ctx; }
