import { formatRupiah } from "./business-utils";

type ReportTransaction = { type: "income" | "expense"; amount: number; date: string };
function escapeHtml(value: string) { return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character); }

export function buildUmkmKuReport({ monthLabel, transactions, income, expense, profile, language }: { monthLabel: string; transactions: ReportTransaction[]; income: number; expense: number; profile: { businessName: string; ownerName: string; logoUri: string | null }; language: "id" | "en" }) {
  const days = new Map<string, { date: Date; income: number; expense: number }>();
  transactions.forEach((transaction) => { const key = new Date(transaction.date).toISOString().slice(0, 10); const current = days.get(key) ?? { date: new Date(transaction.date), income: 0, expense: 0 }; current[transaction.type] += transaction.amount; days.set(key, current); });
  const rows = [...days.values()].sort((a, b) => a.date.getTime() - b.date.getTime()).map((day) => { const profit = day.income - day.expense; return `<tr><td>${day.date.toLocaleDateString("id-ID", { weekday: "short", day: "numeric", month: "short" })}</td><td>${formatRupiah(day.income)}</td><td>${formatRupiah(day.expense)}</td><td class="${profit >= 0 ? "profit" : "loss"}">${profit >= 0 ? "+" : "−"} ${formatRupiah(Math.abs(profit))}</td><td class="${profit >= 0 ? "profit" : "loss"}">${profit >= 0 ? (language === "id" ? "Untung" : "Profit") : (language === "id" ? "Rugi" : "Loss")}</td></tr>`; }).join("") || `<tr><td colspan="5" class="empty">${language === "id" ? "Belum ada transaksi pada periode ini." : "No transactions for this period yet."}</td></tr>`;
  const balance = income - expense; const generatedAt = new Date().toLocaleString(language === "id" ? "id-ID" : "en-US", { dateStyle: "medium", timeStyle: "short" });
  const copy = language === "id" ? { subtitle: "Laporan Keuangan Harian", printed: "Dicetak", owner: "Pemilik", period: "Periode", income: "TOTAL PEMASUKAN", expense: "TOTAL PENGELUARAN", profit: "UNTUNG BERSIH", detail: "Rincian Harian", total: "TOTAL", source: "Dihasilkan otomatis oleh UMKM KU dari data catatan yang tersimpan di perangkat ini. Dokumen ini merupakan ringkasan pembukuan dan bukan dokumen resmi perpajakan." } : { subtitle: "Daily Financial Report", printed: "Printed", owner: "Owner", period: "Period", income: "TOTAL INCOME", expense: "TOTAL EXPENSE", profit: "NET PROFIT", detail: "Daily Details", total: "TOTAL", source: "Generated automatically by UMKM KU from transaction records stored on this device. This document is a bookkeeping summary and not an official tax document." };
  const logo = profile.logoUri ? `<img src="${escapeHtml(profile.logoUri)}" class="logo"/>` : "";
  return `<!DOCTYPE html><html><head><meta charset="utf-8"/><style>@page{size:A4;margin:18mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#29435B;margin:0}.head{display:flex;align-items:center;gap:12px}.logo{width:42px;height:42px;object-fit:contain;border-radius:8px}.brand{font-size:22px;font-weight:800;color:#2D6EAE;letter-spacing:.2px}.subtitle{font-size:13px;color:#718292;margin-top:3px}.printed{font-size:10px;color:#718292;margin-top:7px}.business{margin:34px 0 26px}.business h1{font-size:23px;line-height:1.2;margin:0 0 5px}.business p{font-size:12px;color:#536A7D;margin:0}.totals{display:flex;gap:24px;margin-bottom:28px}.total{flex:1}.total label{display:block;font-size:10px;color:#718292;font-weight:700;margin-bottom:5px}.total strong{font-size:20px}.income,.profit{color:#1C8C71}.expense,.loss{color:#C14857}.balance{color:#29435B}.table-title{font-size:13px;font-weight:800;margin-bottom:8px}table{width:100%;border-collapse:collapse;font-size:11px}th{text-align:left;color:#718292;font-size:10px;font-weight:700;padding:9px 6px;border-bottom:1px solid #E2E9ED}td{padding:10px 6px;border-bottom:1px solid #EEF3F6;font-weight:600}.total-row td{font-weight:800;color:#29435B;border-top:2px solid #2D6EAE;border-bottom:0}.empty{text-align:center;color:#718292;padding:22px}.footer{margin-top:26px;border-top:1px solid #E2E9ED;padding-top:10px;color:#718292;font-size:9px;line-height:1.5}</style></head><body><div class="head">${logo}<div><div class="brand">UMKM KU</div><div class="subtitle">${copy.subtitle}</div><div class="printed">${copy.printed}: ${escapeHtml(generatedAt)}</div></div></div><section class="business"><h1>${escapeHtml(profile.businessName)}</h1><p>${copy.owner}: ${escapeHtml(profile.ownerName)} · ${copy.period}: ${escapeHtml(monthLabel)}</p></section><section class="totals"><div class="total"><label>${copy.income}</label><strong class="income">${formatRupiah(income)}</strong></div><div class="total"><label>${copy.expense}</label><strong class="expense">${formatRupiah(expense)}</strong></div><div class="total"><label>${copy.profit}</label><strong class="balance">${formatRupiah(balance)}</strong></div></section><div class="table-title">${copy.detail}</div><table><thead><tr><th>${language === "id" ? "Tanggal" : "Date"}</th><th>${language === "id" ? "Pemasukan" : "Income"}</th><th>${language === "id" ? "Pengeluaran" : "Expense"}</th><th>${language === "id" ? "Laba/Rugi" : "Profit/Loss"}</th><th>Status</th></tr></thead><tbody>${rows}<tr class="total-row"><td>${copy.total} ${escapeHtml(monthLabel.toUpperCase())}</td><td>${formatRupiah(income)}</td><td>${formatRupiah(expense)}</td><td>${balance >= 0 ? "+" : "−"} ${formatRupiah(Math.abs(balance))}</td><td>${balance >= 0 ? (language === "id" ? "UNTUNG" : "PROFIT") : (language === "id" ? "RUGI" : "LOSS")}</td></tr></tbody></table><footer class="footer">${copy.source}</footer></body></html>`;
}
