import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { BantuUsahaMark, BrandIcon, type BrandIconName } from "@/components/brand-assets";
import { GradientPanel } from "@/components/gradient-panel";
import { ScreenContainer } from "@/components/screen-container";
import { lessons, services } from "@/lib/business-content";
import { useBusinessStore } from "@/lib/business-store";
import { useThemeContext } from "@/lib/theme-provider";
type Item = { type: "service" | "lesson"; id: string };
const items: Item[] = [...services.map((entry) => ({ type: "service" as const, id: entry.id })), ...lessons.slice(0, 3).map((entry) => ({ type: "lesson" as const, id: entry.id }))];
const serviceIcons: Record<string, BrandIconName> = { nib: "permit", halal: "guide", merek: "book", modal: "capital" };
export default function ServicesScreen() { const { completedLessons, profile } = useBusinessStore(); const { colorScheme } = useThemeContext(); const dark = colorScheme === "dark"; const identityReady = profile.businessName !== "Usaha Anda" || Boolean(profile.logoUri); return <ScreenContainer><FlatList data={items} keyExtractor={(item) => `${item.type}-${item.id}`} contentContainerStyle={styles.list} ListHeaderComponent={<><View style={styles.topbar}><View style={styles.brand}><BantuUsahaMark size={27} /><View><Text style={[styles.overline, dark && styles.textDark]}>LAYANAN USAHA</Text><Text style={[styles.title, dark && styles.textDark]}>Usaha Kamu, Kami Dukung</Text></View></View><Pressable onPress={() => router.push("/news")} style={[styles.news, dark && styles.newsDark]}><BrandIcon name="bell" size={20} color={dark ? "#FFFFFF" : "#27476B"} /></Pressable></View><GradientPanel style={styles.hero} colors={["#234E87", "#4D8ABE"]}><Text style={styles.heroBadge}>PUSAT BANTUAN USAHA</Text><Text style={styles.heroTitle}>Layanan penting ada dalam satu tempat.</Text><Text style={styles.heroText}>Siapkan izin, modal, dan kemampuan usaha tanpa istilah yang membuat bingung.</Text></GradientPanel><Text style={[styles.sectionTitle, dark && styles.textDark]}>Akun & progres</Text><Quick icon="capital" title="Profil Usaha" text={profile.businessName} status={identityReady ? "Aktif" : "Lengkapi"} onPress={() => router.push("/business-profile")} dark={dark} /><Quick icon="activity" title="Progres Usaha" text="Lencana & target mingguan" status="Lihat" onPress={() => router.push("/progress")} dark={dark} /><Quick icon="guide" title="Pengaturan" text="Tema & tampilan" status={colorScheme === "dark" ? "Dark aktif" : "Light aktif"} onPress={() => router.push("/preferences")} dark={dark} /><Text style={[styles.sectionTitle, dark && styles.textDark]}>Layanan utama</Text></>} renderItem={({ item, index }) => <ServiceListItem item={item} index={index} doneIds={completedLessons} dark={dark} />} /></ScreenContainer>; }
function ServiceListItem({ item, index, doneIds, dark }: { item: Item; index: number; doneIds: string[]; dark: boolean }) { if (item.type === "service") { const entry = services.find((service) => service.id === item.id)!; const color = ["#2D6EAE", "#A84858", "#5E4BB7", "#386E9F"][services.findIndex((service) => service.id === item.id)]; return <Pressable onPress={() => router.push(`/service/${entry.id}`)} style={[styles.card, dark && styles.cardDark]}><View style={styles.cardIcon}><BrandIcon name={serviceIcons[entry.id]} size={22} color={color} /></View><View style={styles.grow}><Text style={[styles.cardTitle, dark && styles.textDark]}>{entry.title}</Text><Text style={[styles.cardText, dark && styles.mutedDark]} numberOfLines={2}>{entry.summary}</Text></View><BrandIcon name="arrow" size={18} color="#2D6EAE" /></Pressable>; } const lesson = lessons.find((entry) => entry.id === item.id)!; const done = doneIds.includes(lesson.id); return <View>{index === services.length ? <Text style={[styles.sectionTitle, dark && styles.textDark]}>Belajar Mandiri</Text> : null}<Pressable onPress={() => router.push(`/lesson/${lesson.id}`)} style={[styles.card, dark && styles.cardDark]}><View style={styles.cardIcon}><BrandIcon name={done ? "activity" : "academy"} size={22} color={done ? "#168B72" : "#5E4BB7"} /></View><View style={styles.grow}><Text style={[styles.cardTitle, dark && styles.textDark]}>{lesson.title}</Text><Text style={[styles.cardText, dark && styles.mutedDark]}>{done ? "Sudah selesai" : lesson.duration}</Text></View><BrandIcon name="arrow" size={18} color="#2D6EAE" /></Pressable></View>; }
function Quick({ icon, title, text, status, onPress, dark }: { icon: BrandIconName; title: string; text: string; status: string; onPress: () => void; dark: boolean }) { return <Pressable onPress={onPress} style={[styles.quick, dark && styles.cardDark]}><View style={styles.cardIcon}><BrandIcon name={icon} size={20} color="#2D6EAE" /></View><View style={styles.grow}><Text style={[styles.cardTitle, dark && styles.textDark]}>{title}</Text><Text style={[styles.cardText, dark && styles.mutedDark]}>{text}</Text></View><Text style={styles.status}>{status}</Text><BrandIcon name="arrow" size={16} color="#2D6EAE" /></Pressable>; }
const styles = StyleSheet.create({ list: { paddingHorizontal: 16, paddingBottom: 30 }, grow: { flex: 1 }, topbar: { paddingTop: 9, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, brand: { flexDirection: "row", alignItems: "center", gap: 7 }, overline: { color: "#8293A2", fontSize: 9, fontWeight: "900", letterSpacing: 0.8 }, title: { color: "#29435B", fontSize: 19, fontWeight: "900", marginTop: 1 }, news: { width: 38, height: 38, borderRadius: 14, backgroundColor: "#F0F6FA", alignItems: "center", justifyContent: "center" }, newsDark: { backgroundColor: "#172235", borderWidth: 1, borderColor: "#2A3B54" }, hero: { minHeight: 178, borderRadius: 21, padding: 17, paddingBottom: 20, marginTop: 16 }, heroBadge: { color: "#2D6EAE", fontSize: 8, fontWeight: "900", backgroundColor: "#FFFFFF", paddingHorizontal: 8, paddingVertical: 5, alignSelf: "flex-start", borderRadius: 9 }, heroTitle: { color: "#FFFFFF", fontSize: 20, lineHeight: 25, fontWeight: "900", marginTop: 13 }, heroText: { color: "#FFFFFF", fontSize: 10, lineHeight: 15, marginTop: 6 }, sectionTitle: { color: "#2A3E52", fontSize: 15, fontWeight: "900", marginTop: 20, marginBottom: 9 }, quick: { minHeight: 62, borderRadius: 13, borderWidth: 1, borderColor: "#E2E9ED", backgroundColor: "#FFFFFF", padding: 10, flexDirection: "row", alignItems: "center", gap: 9, marginBottom: 8 }, card: { minHeight: 72, borderRadius: 13, borderWidth: 1, borderColor: "#E2E9ED", backgroundColor: "#FFFFFF", padding: 11, marginBottom: 8, flexDirection: "row", alignItems: "center", gap: 10 }, cardDark: { backgroundColor: "#172235", borderColor: "#2A3B54" }, cardIcon: { width: 40, height: 40, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#E6F3FA" }, cardTitle: { color: "#29435B", fontSize: 12, fontWeight: "900" }, cardText: { color: "#718292", fontSize: 9, marginTop: 3 }, status: { color: "#168B72", fontSize: 8, fontWeight: "900", backgroundColor: "#E3F7F0", borderRadius: 8, paddingHorizontal: 6, paddingVertical: 4 }, textDark: { color: "#FFFFFF" }, mutedDark: { color: "#FFFFFF" } });
