import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { AppButton } from "@/components/ui/app-button";
import { ScreenBack } from "@/components/screen-back";
import { ScreenContainer } from "@/components/screen-container";
import { guides } from "@/lib/business-content";
import { useBusinessStore } from "@/lib/business-store";

export default function GuideDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const guide = guides.find((item) => item.id === id);
  const { guideProgress, toggleGuideStep } = useBusinessStore();
  if (!guide) return <ScreenContainer className="p-5"><ScreenBack title="Panduan" /><Text style={styles.notFound}>Panduan tidak ditemukan.</Text></ScreenContainer>;
  const completed = guideProgress[guide.id] ?? [];
  const percentage = Math.round((completed.length / guide.steps.length) * 100);
  const allDone = completed.length === guide.steps.length;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><FlatList data={guide.steps} keyExtractor={(item, index) => `${item}-${index}`} contentContainerStyle={styles.list} ListHeaderComponent={<><ScreenBack title="Panduan" /><View style={styles.hero}><View style={styles.heroTop}><View><Text style={styles.heroEyebrow}>PANDUAN PRAKTIS</Text><Text style={styles.heroTitle}>{guide.title}</Text></View><View style={styles.heroNumber}><Text style={styles.heroNumberText}>{percentage}%</Text></View></View><Text style={styles.heroText}>{guide.summary}</Text><View style={styles.track}><View style={[styles.trackValue, { width: `${percentage}%` }]} /></View><Text style={styles.heroCaption}>{completed.length} dari {guide.steps.length} langkah sudah Anda tandai</Text></View><Text style={styles.heading}>Langkah yang bisa dilakukan</Text><Text style={styles.subheading}>Ketuk satu langkah saat Anda sudah menyelesaikannya.</Text></>} renderItem={({ item, index }) => { const done = completed.includes(index); return <Pressable onPress={() => toggleGuideStep(guide.id, index)} style={({ pressed }) => [styles.step, done && styles.stepDone, pressed && styles.pressed]} accessibilityRole="checkbox" accessibilityState={{ checked: done }}><View style={[styles.stepIndex, done && styles.stepIndexDone]}>{done ? <MaterialIcons name="check" size={16} color="#FFFFFF" /> : <Text style={styles.stepIndexText}>0{index + 1}</Text>}</View><Text style={[styles.stepText, done && styles.stepTextDone]}>{item}</Text></Pressable>; }} ListFooterComponent={<View style={styles.footer}>{allDone ? <><View style={styles.completed}><MaterialIcons name="verified" size={22} color="#127352" /><Text style={styles.completedText}>Panduan ini sudah Anda selesaikan.</Text></View><AppButton label="Pilih panduan lain" variant="primary" icon="arrow-forward" onPress={() => router.replace("/guide")} /></> : <AppButton label="Simpan progres & kembali" variant="primary" icon="arrow-forward" onPress={() => router.replace("/guide")} />}</View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ list: { padding: 20, paddingTop: 8, paddingBottom: 36 }, notFound: { color: "#14211F", fontSize: 16 }, hero: { borderRadius: 26, padding: 20, backgroundColor: "#124C43", marginTop: 2 }, heroTop: { flexDirection: "row", justifyContent: "space-between", gap: 14 }, heroEyebrow: { color: "#BED7CC", fontSize: 11, fontWeight: "800", letterSpacing: 1.05 }, heroTitle: { color: "#FFFFFF", fontSize: 26, lineHeight: 32, fontWeight: "800", marginTop: 5, maxWidth: 210 }, heroNumber: { width: 48, height: 48, borderRadius: 16, backgroundColor: "#E9B653", alignItems: "center", justifyContent: "center" }, heroNumberText: { color: "#4A3510", fontSize: 13, fontWeight: "900" }, heroText: { color: "#D8EAE3", fontSize: 14, lineHeight: 21, marginTop: 17 }, track: { height: 8, backgroundColor: "#3C756A", borderRadius: 8, overflow: "hidden", marginTop: 18 }, trackValue: { height: 8, backgroundColor: "#E9B653", borderRadius: 8 }, heroCaption: { color: "#BED7CC", fontSize: 12, fontWeight: "700", marginTop: 10 }, heading: { color: "#14211F", fontSize: 20, lineHeight: 26, fontWeight: "800", marginTop: 26 }, subheading: { color: "#5E706B", fontSize: 14, lineHeight: 21, marginTop: 4, marginBottom: 3 }, step: { minHeight: 78, backgroundColor: "#FFFFFF", borderRadius: 19, borderWidth: 1, borderColor: "#E0E7E3", padding: 15, marginTop: 10, flexDirection: "row", alignItems: "center", gap: 13 }, stepDone: { borderColor: "#B9DCCB", backgroundColor: "#F1F8F4" }, stepIndex: { width: 34, height: 34, borderRadius: 12, backgroundColor: "#E8F3EE", alignItems: "center", justifyContent: "center" }, stepIndexDone: { backgroundColor: "#127352" }, stepIndexText: { color: "#124C43", fontSize: 12, fontWeight: "900" }, stepText: { flex: 1, color: "#14211F", fontSize: 15, lineHeight: 21, fontWeight: "700" }, stepTextDone: { color: "#457060", textDecorationLine: "line-through" }, footer: { marginTop: 26 }, completed: { flexDirection: "row", alignItems: "center", gap: 9, borderRadius: 16, backgroundColor: "#E8F3EE", padding: 13, marginBottom: 12 }, completedText: { color: "#127352", fontSize: 14, fontWeight: "800" }, pressed: { opacity: 0.78, transform: [{ scale: 0.985 }] } });
